### ISSUE TITLE
Crashes since "Components upgrade" or "Fav apps on home screen"

### ISSUE THREAD

**Issue by m-hugo** [iamrasel/lunar-launcher#109]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

2.8.1 and 2.8.1.1 | github and fdroid

### Android version

13

### Steps to reproduce the bug

crashes at startup

### Logs

```
Caused by: java.lang.NumberFormatException: For input string: "res/color-v31/m3_ref_palette_dynamic_neutral_variant6.xml" under radix 16
01-16 11:29:35.623  8700  8700 E AndroidRuntime: 	at java.lang.Long.parseLong(Long.java:751)
01-16 11:29:35.623  8700  8700 E AndroidRuntime: 	at android.graphics.Color.parseColor(Color.java:1385)
01-16 11:29:35.623  8700  8700 E AndroidRuntime: 	at rasel.lunar.launcher.LauncherActivity.onResume(Unknown Source:205)
```

### Additional information

only the 2 latest CI_Push crash https://github.com/iamrasel/lunar-launcher/actions/runs/7438657970 works

**Comment by m-hugo** [comment]
@iamrasel you should fix it soon, a startup crash is VERY BAD, especially for a launcher

**Comment by ottop** [comment]
I have noticed the same issue on the 2.8.1.1 version from both, F-Droid and the GitHub as well as version 2.8.1. 

One more interesting detail that I can add is that while the launcher itself does not launch, it is possible to launch the launcher's settings from App Info -> Additional settings in the app. 

In the settings menu, all of the items are accessible except for appearances, clicking on which crashes the launcher. The resulting error has to do with the same input string, so it seems to be related.

Here is my crash log for starting the launcher:
```
type: crash
osVersion: Fairphone/FP4eea/FP4:13/TQ3A.230901.001/eng.emy.20240107.055631:user/release-keys
package: rasel.lunar.launcher:37
process: rasel.lunar.launcher

java.lang.RuntimeException: Unable to resume activity {rasel.lunar.launcher/rasel.lunar.launcher.LauncherActivity}: java.lang.NumberFormatException: For input string: "res/color-v31/m3_ref_palette_dynamic_neutral_variant6.xml"
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4774)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4807)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:179)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.NumberFormatException: For input string: "res/color-v31/m3_ref_palette_dynamic_neutral_variant6.xml"
	at java.lang.Long.parseLong(Long.java:736)
	at android.graphics.Color.parseColor(Color.java:1385)
	at rasel.lunar.launcher.LauncherActivity.onResume(Unknown Source:205)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1564)
	at android.app.Activity.performResume(Activity.java:8474)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4764)
	... 15 more

```

**Comment by ottop** [comment]
I made a PR to fix this issue:
#110
