### ISSUE TITLE
Unable to load a wallpaper

### ISSUE THREAD

**Issue by The-Repo-Club** [iamrasel/lunar-launcher#38]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

2.2.2

### Android version

13

### Steps to reproduce the bug

click the change background button and screen just flashes

### Expected behavior

to pop up to change the wallpaper

### Additional information

setting a wallpaper with the default way with google pixel 7 then changing the background of the app to be transparent does work though.

**Comment by iamrasel** [comment]
Can you please provide the logcat of that moment when the `screen just flashes` and do nothing? Also a screen recording would be helpful.

**Comment by The-Repo-Club** [comment]
![Peek 2023-01-01 19-21](https://user-images.githubusercontent.com/9284733/210182348-67d6c3cf-a5ab-4087-b172-47440f336305.gif)

```
2023-01-01 19:21:33.192 3323-3428/rasel.lunar.launcher.debug D/EGL_emulation: app_time_stats: avg=7.84ms min=1.20ms max=146.58ms count=31
2023-01-01 19:21:34.458 3323-3428/rasel.lunar.launcher.debug D/EGL_emulation: app_time_stats: avg=14.24ms min=1.12ms max=279.34ms count=32
2023-01-01 19:21:35.758 3323-3428/rasel.lunar.launcher.debug D/EGL_emulation: app_time_stats: avg=12.26ms min=1.11ms max=293.46ms count=32
2023-01-01 19:21:36.764 3323-3428/rasel.lunar.launcher.debug D/EGL_emulation: app_time_stats: avg=2.91ms min=1.14ms max=21.83ms count=31
2023-01-01 19:21:37.765 3323-3428/rasel.lunar.launcher.debug D/EGL_emulation: app_time_stats: avg=15.23ms min=1.15ms max=279.66ms count=23
2023-01-01 19:21:38.767 3323-3428/rasel.lunar.launcher.debug D/EGL_emulation: app_time_stats: avg=1.66ms min=1.19ms max=5.80ms count=30
2023-01-01 19:21:39.784 3323-3428/rasel.lunar.launcher.debug D/EGL_emulation: app_time_stats: avg=1.57ms min=1.25ms max=2.20ms count=30
2023-01-01 19:21:40.800 3323-3428/rasel.lunar.launcher.debug D/EGL_emulation: app_time_stats: avg=8.50ms min=1.17ms max=157.47ms count=27
2023-01-01 19:21:41.804 3323-3428/rasel.lunar.launcher.debug D/EGL_emulation: app_time_stats: avg=16.97ms min=1.18ms max=307.41ms count=22
2023-01-01 19:21:42.818 3323-3428/rasel.lunar.launcher.debug D/EGL_emulation: app_time_stats: avg=2.61ms min=1.19ms max=10.79ms count=29
2023-01-01 19:21:43.858 3323-3428/rasel.lunar.launcher.debug D/EGL_emulation: app_time_stats: avg=13.04ms min=1.11ms max=251.58ms count=25
```

**Comment by iamrasel** [comment]
@The-Repo-Club The portion of log you provided, is not really helpful. Maybe the app throws an exception, you need to get that part.

**Comment by The-Repo-Club** [comment]
```
2023-01-03 13:59:13.944 8120-8120/rasel.lunar.launcher.debug W/System.err: java.io.IOException: Cannot run program "su": error=13, Permission denied
2023-01-03 13:59:13.944 8120-8120/rasel.lunar.launcher.debug W/System.err:     at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
2023-01-03 13:59:13.944 8120-8120/rasel.lunar.launcher.debug W/System.err:     at java.lang.Runtime.exec(Runtime.java:694)
2023-01-03 13:59:13.944 8120-8120/rasel.lunar.launcher.debug W/System.err:     at java.lang.Runtime.exec(Runtime.java:524)
2023-01-03 13:59:13.944 8120-8120/rasel.lunar.launcher.debug W/System.err:     at java.lang.Runtime.exec(Runtime.java:421)
2023-01-03 13:59:13.944 8120-8120/rasel.lunar.launcher.debug W/System.err:     at rasel.lunar.launcher.helpers.UniUtils$Companion.isRooted(UniUtils.kt:114)
2023-01-03 13:59:13.944 8120-8120/rasel.lunar.launcher.debug W/System.err:     at rasel.lunar.launcher.settings.childs.Misc.onCreateView(Misc.kt:77)
2023-01-03 13:59:13.944 8120-8120/rasel.lunar.launcher.debug W/System.err:     at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
2023-01-03 13:59:13.944 8120-8120/rasel.lunar.launcher.debug W/System.err:     at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:489)
2023-01-03 13:59:13.944 8120-8120/rasel.lunar.launcher.debug W/System.err:     at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
2023-01-03 13:59:13.944 8120-8120/rasel.lunar.launcher.debug W/System.err:     at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
2023-01-03 13:59:13.944 8120-8120/rasel.lunar.launcher.debug W/System.err:     at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
2023-01-03 13:59:13.944 8120-8120/rasel.lunar.launcher.debug W/System.err:     at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
2023-01-03 13:59:13.944 8120-8120/rasel.lunar.launcher.debug W/System.err:     at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
2023-01-03 13:59:13.945 8120-8120/rasel.lunar.launcher.debug W/System.err:     at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
2023-01-03 13:59:13.945 8120-8120/rasel.lunar.launcher.debug W/System.err:     at android.os.Handler.handleCallback(Handler.java:942)
2023-01-03 13:59:13.945 8120-8120/rasel.lunar.launcher.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2023-01-03 13:59:13.945 8120-8120/rasel.lunar.launcher.debug W/System.err:     at android.os.Looper.loopOnce(Looper.java:201)
2023-01-03 13:59:13.945 8120-8120/rasel.lunar.launcher.debug W/System.err:     at android.os.Looper.loop(Looper.java:288)
2023-01-03 13:59:13.945 8120-8120/rasel.lunar.launcher.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7872)
2023-01-03 13:59:13.945 8120-8120/rasel.lunar.launcher.debug W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2023-01-03 13:59:13.945 8120-8120/rasel.lunar.launcher.debug W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
2023-01-03 13:59:13.945 8120-8120/rasel.lunar.launcher.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2023-01-03 13:59:13.945 8120-8120/rasel.lunar.launcher.debug W/System.err: Caused by: java.io.IOException: error=13, Permission denied
2023-01-03 13:59:13.945 8120-8120/rasel.lunar.launcher.debug W/System.err:     at java.lang.UNIXProcess.forkAndExec(Native Method)
2023-01-03 13:59:13.945 8120-8120/rasel.lunar.launcher.debug W/System.err:     at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
2023-01-03 13:59:13.945 8120-8120/rasel.lunar.launcher.debug W/System.err:     at java.lang.ProcessImpl.start(ProcessImpl.java:141)
2023-01-03 13:59:13.945 8120-8120/rasel.lunar.launcher.debug W/System.err:     at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
2023-01-03 13:59:13.945 8120-8120/rasel.lunar.launcher.debug W/System.err: 	... 21 more
```

**Comment by The-Repo-Club** [comment]
once i gave it permission though it still did the flashing but no errors given too

**Comment by The-Repo-Club** [comment]
if this helps any this is the full verbos from when i build until i click that button

```
2023-01-04 17:05:06.589 9150-9150/? I/.launcher.debug: Late-enabling -Xcheck:jni
2023-01-04 17:05:06.647 9150-9150/? W/.launcher.debug: Unexpected CPU variant for x86: x86_64.
    Known variants: atom, sandybridge, silvermont, kabylake, default
2023-01-04 17:05:06.708 9150-9150/? V/studio.deploy: Startup agent attached to VM
2023-01-04 17:05:06.710 9150-9150/? V/studio.deploy: No existing instrumentation found. Loading instrumentation from instruments-6b5afa68.jar
2023-01-04 17:05:06.718 9150-9150/? W/.launcher.debug: DexFile /data/data/rasel.lunar.launcher.debug/code_cache/.studio/instruments-6b5afa68.jar is in boot class path but is not in a known location
2023-01-04 17:05:06.723 9150-9150/rasel.lunar.launcher.debug V/studio.deploy: ModifyParameterTransform failed: Landroid/app/ApplicationLoaders;
2023-01-04 17:05:06.725 9150-9150/rasel.lunar.launcher.debug W/.launcher.debug: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
2023-01-04 17:05:06.731 9150-9150/rasel.lunar.launcher.debug W/.launcher.debug: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
2023-01-04 17:05:06.733 9150-9150/rasel.lunar.launcher.debug W/.launcher.debug: Redefining intrinsic method java.lang.Thread java.lang.Thread.currentThread(). This may cause the unexpected use of the original definition of java.lang.Thread java.lang.Thread.currentThread()in methods that have already been compiled.
2023-01-04 17:05:06.733 9150-9150/rasel.lunar.launcher.debug W/.launcher.debug: Redefining intrinsic method boolean java.lang.Thread.interrupted(). This may cause the unexpected use of the original definition of boolean java.lang.Thread.interrupted()in methods that have already been compiled.
2023-01-04 17:05:06.734 9150-9150/rasel.lunar.launcher.debug W/.launcher.debug: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
2023-01-04 17:05:06.739 9150-9150/rasel.lunar.launcher.debug W/.launcher.debug: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
2023-01-04 17:05:06.744 9150-9150/rasel.lunar.launcher.debug W/.launcher.debug: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
2023-01-04 17:05:06.748 9150-9150/rasel.lunar.launcher.debug D/CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10159; state: ENABLED
2023-01-04 17:05:06.759 9150-9150/rasel.lunar.launcher.debug W/ziparchive: Unable to open '/data/app/~~jZo0RP7hfNykuCi40ytOOQ==/rasel.lunar.launcher.debug-ney6DmH9lRzOX1VDMB8aBg==/base.dm': No such file or directory
2023-01-04 17:05:06.759 9150-9150/rasel.lunar.launcher.debug W/ziparchive: Unable to open '/data/app/~~jZo0RP7hfNykuCi40ytOOQ==/rasel.lunar.launcher.debug-ney6DmH9lRzOX1VDMB8aBg==/base.dm': No such file or directory
2023-01-04 17:05:06.879 9150-9150/rasel.lunar.launcher.debug D/nativeloader: Configuring classloader-namespace for other apk /data/app/~~jZo0RP7hfNykuCi40ytOOQ==/rasel.lunar.launcher.debug-ney6DmH9lRzOX1VDMB8aBg==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~jZo0RP7hfNykuCi40ytOOQ==/rasel.lunar.launcher.debug-ney6DmH9lRzOX1VDMB8aBg==/lib/x86_64, permitted_path=/data:/mnt/expand:/data/user/0/rasel.lunar.launcher.debug
2023-01-04 17:05:06.886 9150-9150/rasel.lunar.launcher.debug V/GraphicsEnvironment: ANGLE Developer option for 'rasel.lunar.launcher.debug' set to: 'default'
2023-01-04 17:05:06.886 9150-9150/rasel.lunar.launcher.debug V/GraphicsEnvironment: ANGLE GameManagerService for rasel.lunar.launcher.debug: false
2023-01-04 17:05:06.886 9150-9150/rasel.lunar.launcher.debug V/GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
2023-01-04 17:05:06.889 9150-9150/rasel.lunar.launcher.debug D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2023-01-04 17:05:06.889 9150-9150/rasel.lunar.launcher.debug D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2023-01-04 17:05:06.907 9150-9177/rasel.lunar.launcher.debug D/libEGL: loaded /vendor/lib64/egl/libEGL_emulation.so
2023-01-04 17:05:06.909 9150-9177/rasel.lunar.launcher.debug D/libEGL: loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
2023-01-04 17:05:06.911 9150-9177/rasel.lunar.launcher.debug D/libEGL: loaded /vendor/lib64/egl/libGLESv2_emulation.so
2023-01-04 17:05:06.970 9150-9150/rasel.lunar.launcher.debug D/CompatibilityChangeReporter: Compat change id reported: 210923482; UID 10159; state: ENABLED
2023-01-04 17:05:06.976 9150-9150/rasel.lunar.launcher.debug D/CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10159; state: ENABLED
2023-01-04 17:05:07.033 9150-9150/rasel.lunar.launcher.debug W/.launcher.debug: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
2023-01-04 17:05:07.033 9150-9150/rasel.lunar.launcher.debug W/.launcher.debug: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
2023-01-04 17:05:07.075 9150-9175/rasel.lunar.launcher.debug D/HostConnection: createUnique: call
2023-01-04 17:05:07.076 9150-9175/rasel.lunar.launcher.debug D/HostConnection: HostConnection::get() New Host Connection established 0x7b58f5cfea50, tid 9175
2023-01-04 17:05:07.089 9150-9175/rasel.lunar.launcher.debug D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma ANDROID_EMU_hwc_multi_configs GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_1 
2023-01-04 17:05:07.093 9150-9175/rasel.lunar.launcher.debug W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
2023-01-04 17:05:07.093 9150-9175/rasel.lunar.launcher.debug W/OpenGLRenderer: Failed to initialize 101010-2 format, error = EGL_SUCCESS
2023-01-04 17:05:07.094 9150-9175/rasel.lunar.launcher.debug D/EGL_emulation: eglCreateContext: 0x7b58f5cfec90: maj 3 min 1 rcv 4
2023-01-04 17:05:07.095 9150-9175/rasel.lunar.launcher.debug D/EGL_emulation: eglMakeCurrent: 0x7b58f5cfec90: ver 3 1 (tinfo 0x7b5b125f8080) (first time)
2023-01-04 17:05:07.113 9150-9175/rasel.lunar.launcher.debug I/Gralloc4: mapper 4.x is not supported
2023-01-04 17:05:07.114 9150-9175/rasel.lunar.launcher.debug D/HostConnection: createUnique: call
2023-01-04 17:05:07.114 9150-9175/rasel.lunar.launcher.debug D/HostConnection: HostConnection::get() New Host Connection established 0x7b58f5cfd9d0, tid 9175
2023-01-04 17:05:07.114 9150-9175/rasel.lunar.launcher.debug D/goldfish-address-space: allocate: Ask for block of size 0x100
2023-01-04 17:05:07.114 9150-9175/rasel.lunar.launcher.debug D/goldfish-address-space: allocate: ioctl allocate returned offset 0x3efffe000 size 0x2000
2023-01-04 17:05:07.134 9150-9175/rasel.lunar.launcher.debug W/Gralloc4: allocator 4.x is not supported
2023-01-04 17:05:07.151 9150-9175/rasel.lunar.launcher.debug D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma ANDROID_EMU_hwc_multi_configs GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_1 
2023-01-04 17:05:07.207 9150-9175/rasel.lunar.launcher.debug W/Parcel: Expecting binder but got null!
2023-01-04 17:05:08.671 9150-9175/rasel.lunar.launcher.debug D/EGL_emulation: app_time_stats: avg=136.29ms min=1.21ms max=1312.79ms count=10
2023-01-04 17:05:09.016 9150-9175/rasel.lunar.launcher.debug W/Parcel: Expecting binder but got null!
2023-01-04 17:05:10.173 9150-9175/rasel.lunar.launcher.debug D/EGL_emulation: app_time_stats: avg=127.15ms min=3.34ms max=945.77ms count=9
2023-01-04 17:05:10.277 9150-9150/rasel.lunar.launcher.debug D/CompatibilityChangeReporter: Compat change id reported: 78294732; UID 10159; state: ENABLED
2023-01-04 17:05:10.283 9150-9159/rasel.lunar.launcher.debug I/.launcher.debug: Compiler allocated 4533KB to compile void android.view.ViewRootImpl.performTraversals()
```

**Comment by iamrasel** [comment]
@The-Repo-Club I really can't see any error message which might cause the problem you mentioned. The reason behind the issue you're facing is maybe the android 13's storage access permission system.

**Comment by The-Repo-Club** [comment]
@iamrasel not really the best of ways but i seem to have fixed it by changing this function to be this

```kotlin
    private fun selectWallpaper() {
        try {
            if (requireActivity().checkSelfPermission(READ_MEDIA_IMAGES) != PackageManager.PERMISSION_GRANTED) {
                requireActivity().requestPermissions(arrayOf(READ_MEDIA_IMAGES), 1)
            } else {
                wallpaperChangeLauncher.launch(Intent(Intent.ACTION_PICK).setType("image/*"))
            }
        } catch (e: Exception) {
            if (requireActivity().checkSelfPermission(READ_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED) {
                requireActivity().requestPermissions(arrayOf(READ_EXTERNAL_STORAGE), 1)
            } else {
                wallpaperChangeLauncher.launch(Intent(Intent.ACTION_PICK).setType("image/*"))
            }
        }
    }
```

**Comment by The-Repo-Club** [comment]
your welcome :) glad i could help some
