### ISSUE TITLE
Crash when opening app drawer

### ISSUE THREAD

**Issue by OGBack2Life** [iamrasel/lunar-launcher#44]
### Checklist

- [x] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

2.3

### Android version

13

### Steps to reproduce the bug

Simply opening the app drawer caused the crash 

### Expected behavior

For the application drawer to open 

### Logs

java.lang.IllegalStateException: Slider value(311.0) must be greater or equal to valueFrom(0.0), and lower or equal to valueTo(255.0)
	at h2.c.v(Unknown Source:200)
	at h2.c.onDraw(Unknown Source:7)
	at android.view.View.draw(View.java:23323)
	at android.view.View.updateDisplayListIfDirty(View.java:22182)
	at android.view.View.draw(View.java:23048)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.updateDisplayListIfDirty(View.java:22171)
	at android.view.View.draw(View.java:23048)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.updateDisplayListIfDirty(View.java:22171)
	at android.view.View.draw(View.java:23048)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.draw(View.java:23328)
	at android.view.View.updateDisplayListIfDirty(View.java:22182)
	at android.view.View.draw(View.java:23048)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(Unknown Source:13)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.updateDisplayListIfDirty(View.java:22171)
	at android.view.View.draw(View.java:23048)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.updateDisplayListIfDirty(View.java:22171)
	at android.view.View.draw(View.java:23048)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.updateDisplayListIfDirty(View.java:22171)
	at android.view.View.draw(View.java:23048)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.updateDisplayListIfDirty(View.java:22171)
	at android.view.View.draw(View.java:23048)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.updateDisplayListIfDirty(View.java:22171)
	at android.view.View.draw(View.java:23048)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.updateDisplayListIfDirty(View.java:22171)
	at android.view.View.draw(View.java:23048)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.draw(View.java:23328)
	at com.android.internal.policy.DecorView.draw(DecorView.java:892)
	at android.view.View.updateDisplayListIfDirty(View.java:22182)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:690)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:795)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4820)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4521)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3735)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2473)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9328)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1390)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1398)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1040)
	at android.view.Choreographer.doFrame(Choreographer.java:954)
	at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:1289)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8109)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by iamrasel** [comment]
It is a known issue I almost forgot about. It happens with some specific smartphone brands, as their maximum brightness value differs from most of the android devices out there.

I've tried to solve this issue through the last commit. Can you please get the latest build from Actions tab and check if the issue is still there or gone?
